[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_launch = "ESn9HUCzhjXYqSUpMDiSs1JV4znknv4LvHQFxUL3fTBG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
